### PR TITLE
feat:add minio

### PR DESCRIPTION
**Pull request by qinguoyi**
#### What this PR does / why we need it

https://github.com/InftyAI/omnistore/issues/4

Add support minio

#### Which issue(s) this PR fixes
None

#### Special notes for your reviewer
this pr, it mainly includes things：
1. support minio storage
2. add minio integration-ut
3. update docs

image

#### Does this PR introduce a user-facing change?
```release-note
Add support for minio
```

### CODE REVIEW

**Comment by kerthcet** [comment]
Thanks for the PR, I may take more time to review this, I guess tomorrow. Sorry for that.

**Comment by qinguoyi** [comment]
That’s okay, there's no rush.

**Comment by kerthcet** [comment]
Updates:
I'm busy with the kubernetes review work, we're approaching the code freeze, so this maybe later until this weekend. Sorry for that, but I promise it will be finished this week.

**Comment by kerthcet** [comment]
I'll test with AWS s3 to see whether fits as well.

**Pull request merged**
